from typing import Protocol, Optional, Any, Iterator

from .entities import Task


class TaskRepository(Protocol):
    def save(self, entity: Task): ...
    def get_by_id(self, id: int) -> Optional[Task]: ...
    def find(self, spec: Any = None) -> Iterator[Task]: ...
    def remove(self, id: int): ...
