from typing import Protocol, Optional, Iterator

from .entities import Task, Note
from .spec import Spec
from .enums import EntityType


class UnitOfWork(Protocol):
    intertype: "IntertypeRepository"
    tasks: "TaskRepository"
    notes: "NoteRepository"
    
    def commit(self) -> None: ...
    def rollback(self) -> None: ...


class IntertypeRepository(Protocol):
    """
    encapsulates logic that does NOT fit a specific
    entity type
    """
    def resolve_type(self, id: int) -> EntityType | None: ...
    def resolve_type_by_title(self, title: str) -> EntityType | None: ...
    def resolve_id_by_title(self, title: str) -> int | None: ...
    def remove(self, id: int): ...
    def rewrite_subtree_titles(self, old_prefix: str, new_prefix: str): ...


class TaskRepository(Protocol):
    def add(self, entity: Task): ...
    def save(self, entity: Task): ...
    def get_by_id(self, id: int) -> Optional[Task]: ...
    def get_by_title(self, title: str) -> Optional[Task]: ...
    def filter(
        self,
        spec: Spec = None,
        order_by: str = None,
        reverse: bool = False
    ) -> Iterator[Task]: ...

class NoteRepository(Protocol):
    def add(self, entity: Note): ...
    def save(self, entity: Note): ...
    def get_by_id(self, id: int) -> Optional[Note]: ...
    def get_by_title(self, title: str) -> Optional[Note]: ...
    def filter(
        self,
        spec: Spec = None,
        order_by: str = None,
        reverse: bool = False
    ) -> Iterator[Note]: ...
