from typing import Protocol, Optional, Iterator

from .entities import Task
from .spec import Spec


class RepositoryFactory(Protocol):
    def tasks(self) -> "TaskRepository": ...

class SpecCompiler(Protocol):
    def compile(self, spec: Spec): ...


class TaskRepository(Protocol):
    def add(self, entity: Task): ...
    def save(self, entity: Task): ...
    def get_by_id(self, id: int) -> Optional[Task]: ...
    def get_by_title(self, title: str) -> Optional[Task]: ...
    def filter(self, spec: Spec = None) -> Iterator[Task]: ...
    def remove(self, id: int): ...
